# Generated by Django 6.0.1 on 2026-01-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_memberprofile_seat_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('seat_rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utility_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='members.memberprofile')),
            ],
            options={
                'unique_together': {('member', 'month')},
            },
        ),
    ]
